on:
  schedule:
    - cron: "*/2 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    name: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: build
        run: |
          docker build -t test .
  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: deploy
        run: |
          MINWAIT=10;\
          MAXWAIT=30;\
          sleep $((MINWAIT+RANDOM % (MAXWAIT-MINWAIT)))
