on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Set variables for non-PR triggers
      if: github.event_name != 'pull_request'
      run: |
        echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV 
        echo "BRANCH=$GITHUB_REF_NAME" >> $GITHUB_ENV

    - name: Set variables for PR triggers
      if: github.event_name == 'pull_request'
      run: |
        echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV
        echo "BRANCH=$GITHUB_HEAD_REF" >> $GITHUB_ENV

    - name: print variables
      run: |
        echo github.event_name ${{ github.event_name }}
        echo github.event.pull_request.head.sha ${{ github.event.pull_request.head.sha }}
        echo GITHUB_SHA $GITHUB_SHA
        echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
        echo GITHUB_HEAD_REF $GITHUB_HEAD_REF
        echo COMMIT_SHA $COMMIT_SHA
        echo BRANCH $BRANCH

    - uses: actions/checkout@v3
      with:
        ref: ${{ env.COMMIT_SHA }}
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
  
