on:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

    - name: Set commit SHA for PR
      if: github.event_name != 'pull_request'
      run: |
        echo "COMMIT_SHA=$GITHUB_SHA" >> $GITHUB_ENV

    - name: Set commit SHA for non-PR
      if: github.event_name == 'pull_request'
      run: |
        echo "COMMIT_SHA=${{ github.event.pull_request.head.sha }}" >> $GITHUB_ENV

    - name: Docker login, build, push
      run: |
        echo github.event_name ${{ github.event_name }}
        echo github.event.pull_request.head.sha ${{ github.event.pull_request.head.sha }}
        echo GITHUB_SHA $GITHUB_SHA
        echo GITHUB_REPOSITORY $GITHUB_REPOSITORY
        echo GITHUB_HEAD_REF $GITHUB_HEAD_REF
        echo COMMIT_SHA $COMMIT_SHA

    - uses: actions/checkout@v3
      with:
        ref: $COMMIT_SHA
  
